function execute() {
    return Response.success([
        {title: "男-历史",input: "0-56-a",script: "gen.js"},
        {title: "男-穿越历史",input: "0-56-57",script: "gen.js"},
        {title: "男-架空历史",input: "0-56-58",script: "gen.js"},
        {title: "男-历史传记",input: "0-56-59",script: "gen.js"},
        {title: "男-军事",input: "0-60-a",script: "gen.js"},
        {title: "男-现代军事",input: "0-60-61",script: "gen.js"},
        {title: "男-抗战烽火",input: "0-60-62",script: "gen.js"},
        {title: "男-战争幻想",input: "0-60-227",script: "gen.js"},
        {title: "男-科幻",input: "0-64-a",script: "gen.js"},
        {title: "男-星际机甲",input: "0-64-65",script: "gen.js"},
        {title: "男-末世危机",input: "0-64-66",script: "gen.js"},
        {title: "男-未来幻想",input: "0-64-67",script: "gen.js"},
        {title: "男-游戏",input: "0-75-a",script: "gen.js"},
        {title: "男-电子竞技",input: "0-75-78",script: "gen.js"},
        {title: "男-虚拟网游",input: "0-75-232",script: "gen.js"},
        {title: "男-游戏异界",input: "0-75-233",script: "gen.js"},
        {title: "男-玄幻奇幻",input: "0-202-a",script: "gen.js"},
        {title: "男-东方玄幻",input: "0-202-37",script: "gen.js"},
        {title: "男-异界大陆",input: "0-202-39",script: "gen.js"},
        {title: "男-西方奇幻",input: "0-202-41",script: "gen.js"},
        {title: "男-诸天万界",input: "0-202-217",script: "gen.js"},
        {title: "男-王朝争霸",input: "0-202-218",script: "gen.js"},
        {title: "男-都市人生",input: "0-203-a",script: "gen.js"},
        {title: "男-明星娱乐",input: "0-203-46",script: "gen.js"},
        {title: "男-乡村生活",input: "0-203-48",script: "gen.js"},
        {title: "男-异术超能",input: "0-203-219",script: "gen.js"},
        {title: "男-都市高手",input: "0-203-220",script: "gen.js"},
        {title: "男-商战职场",input: "0-203-221",script: "gen.js"},
        {title: "男-热血校园",input: "0-203-222",script: "gen.js"},
        {title: "男-现实百态",input: "0-203-223",script: "gen.js"},
        {title: "男-都市修仙",input: "0-203-224",script: "gen.js"},
        {title: "男-奇闻异事",input: "0-204-a",script: "gen.js"},
        {title: "男-神秘怪谈",input: "0-204-73",script: "gen.js"},
        {title: "男-侦探推理",input: "0-204-228",script: "gen.js"},
        {title: "男-惊心动魄",input: "0-204-229",script: "gen.js"},
        {title: "男-寻宝探险",input: "0-204-230",script: "gen.js"},
        {title: "男-奇门秘术",input: "0-204-231",script: "gen.js"},
        {title: "男-武侠仙侠",input: "0-205-a",script: "gen.js"},
        {title: "男-上古洪荒",input: "0-205-38",script: "gen.js"},
        {title: "男-古典仙侠",input: "0-205-52",script: "gen.js"},
        {title: "男-传统武侠",input: "0-205-54",script: "gen.js"},
        {title: "男-幻想修真",input: "0-205-225",script: "gen.js"},
        {title: "男-国术无双",input: "0-205-226",script: "gen.js"},
        {title: "男-武侠幻想",input: "0-205-237",script: "gen.js"},
        {title: "男-体育",input: "0-206-a",script: "gen.js"},
        {title: "男-其他竞技",input: "0-206-234",script: "gen.js"},
        {title: "男-篮球风云",input: "0-206-235",script: "gen.js"},
        {title: "男-足球天下",input: "0-206-236",script: "gen.js"},
        {title: "男-N次元",input: "0-207-a",script: "gen.js"},
        {title: "男-原生幻想",input: "0-207-238",script: "gen.js"},
        {title: "男-衍生同人",input: "0-207-239",script: "gen.js"},
        {title: "女-现代言情",input: "1-1-a",script: "gen.js"},
        {title: "女-总裁豪门",input: "1-1-8",script: "gen.js"},
        {title: "女-职场情缘",input: "1-1-11",script: "gen.js"},
        {title: "女-民国旧影",input: "1-1-12",script: "gen.js"},
        {title: "女-娱乐明星",input: "1-1-13",script: "gen.js"},
        {title: "女-现实生活",input: "1-1-274",script: "gen.js"},
        {title: "女-青春校园",input: "1-1-275",script: "gen.js"},
        {title: "女-年代重生",input: "1-1-278",script: "gen.js"},
        {title: "女-都市奇幻",input: "1-1-279",script: "gen.js"},
        {title: "女-古代言情",input: "1-2-a",script: "gen.js"},
        {title: "女-种田经商",input: "1-2-16",script: "gen.js"},
        {title: "女-宫闱宅斗",input: "1-2-209",script: "gen.js"},
        {title: "女-古代情缘",input: "1-2-216",script: "gen.js"},
        {title: "女-权谋天下",input: "1-2-280",script: "gen.js"},
        {title: "女-武侠江湖",input: "1-2-281",script: "gen.js"},
        {title: "女-远古大陆",input: "1-2-282",script: "gen.js"},
        {title: "女-幻想言情",input: "1-4-a",script: "gen.js"},
        {title: "女-玄幻仙侠",input: "1-4-21",script: "gen.js"},
        {title: "女-未来科幻",input: "1-4-22",script: "gen.js"},
        {title: "女-无限快穿",input: "1-4-283",script: "gen.js"},
        {title: "女-末世求生",input: "1-4-284",script: "gen.js"},
        {title: "女-异世幻想",input: "1-4-285",script: "gen.js"},
        {title: "女-游戏竞技",input: "1-200-a",script: "gen.js"},
        {title: "女-衍生言情",input: "0-56-58",script: "gen.js"},
        {title: "文学艺术",input: "2-240-a",script: "gen.js"},
        {title: "人物传记",input: "2-240-247",script: "gen.js"},
        {title: "散文随笔",input: "2-240-248",script: "gen.js"},
        {title: "诗词歌赋",input: "2-240-267",script: "gen.js"},
        {title: "评论研究",input: "2-240-268",script: "gen.js"},
        {title: "人文社科",input: "2-241-a",script: "gen.js"},
        {title: "历史文化",input: "2-241-250",script: "gen.js"},
        {title: "心理读物",input: "2-241-272",script: "gen.js"},
        {title: "科普读物",input: "2-241-273",script: "gen.js"},
        {title: "战争军事",input: "2-241-292",script: "gen.js"},
        {title: "思想政治",input: "2-241-293",script: "gen.js"},
        {title: "艺术生活",input: "2-241-294",script: "gen.js"},
        {title: "健康养生",input: "2-241-295",script: "gen.js"},
        {title: "经管励志",input: "2-242-a",script: "gen.js"},
        {title: "成功有道",input: "2-242-296",script: "gen.js"},
        {title: "励志鸡汤",input: "2-242-297",script: "gen.js"},
        {title: "理财经济",input: "2-242-298",script: "gen.js"},
        {title: "企业管理",input: "2-242-299",script: "gen.js"},
        {title: "经典文学",input: "2-243-a",script: "gen.js"},
        {title: "出版小说",input: "2-257-a",script: "gen.js"},
        {title: "古代言情", input: "2-257-259", script: "gen.js"},
        {title: "现代言情", input: "2-257-260", script: "gen.js"},
        {title: "科幻未来", input: "2-257-261", script: "gen.js"},
        {title: "悬疑推理", input: "2-257-262", script: "gen.js"},
        {title: "历史小说", input: "2-257-264", script: "gen.js"},
        {title: "青春文学", input: "2-257-265", script: "gen.js"},
        {title: "现实小说", input: "2-257-266", script: "gen.js"},
        {title: "仙侠奇缘", input: "2-257-276", script: "gen.js"},
        {title: "仙侠玄幻", input: "2-257-288", script: "gen.js"},
        {title: "武侠小说", input: "2-257-289", script: "gen.js"},
        {title: "现代军旅", input: "2-257-290", script: "gen.js"},
        {title: "革命战争", input: "2-257-291", script: "gen.js"},
        {title: "少儿教育", input: "2-258-a", script: "gen.js"},

    ]);
}